### ISSUE TITLE
Weird tag name replacement

### ISSUE THREAD

**Issue by linaori** [yannickl88/features-bundle#1]
Say I have the following configuration:

``` yml
features:
    tags:
        foo.bar-baz: ~
```

The feature tag will be renamed to `foo.bar.baz`, which is not what you expect.
